apiVersion: v1
kind: Service
metadata:
  name: adv-postgres
  namespace: adv-protect
spec:
  selector:
    app: adv-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
