apiVersion: v1
kind: Service
metadata:
  name: adv-api
  namespace: adv-protect
spec:
  selector:
    app: adv-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
